### ISSUE TITLE
&& иногда более к месту чем тернарка

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Inna3112/react-native-project#15]
```
{post ? <Text>My post: {post}</Text> : null}
```
Подобный код можно записать еще вот так
```
{post && <Text>My post: {post}</Text>}
```
НО!
В react-native лучше это сделать вот так 
```
{!!post && <Text>My post: {post}</Text>}
```
Я кажется как-то упоминал что второй пример упадет если в `post` будет пустая строка, так что нужно быть аккуратнее
Выбор записи за тобой

**Comment by Inna3112** [comment]
виправила
