### ISSUE TITLE
Не забывай чистить комментарии в коде

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Inna3112/react-native-project#9]
Нет ничего более постоянного чем временное. Поэтому если код не нужен лучше сразу его удалить

`DrawerNavigator.tsx`
```
// type FeedPropsType = {
//   navigation: DrawerNavigationProp<any>;
// };
```

**Comment by Inna3112** [comment]
Можна в цьому навчальному проекті коментарі залишати? Лише в навчальних цілях. Я в основному залишаю types, щоб потім довго їх не шукати по просторам google)

**Comment by DmitriiMelnikOnix** [comment]
Хорошо, пусть будут)
